#!/usr/bin/env bash

CONTAINER_TAG='htcondor-executor-dev'

set -e

docker build -t ${CONTAINER_TAG} --file docker/Dockerfile .

docker run -it --rm --mount type=bind,src="$PWD",dst=/home/executor/htcondor-executor -p 8000:8000 ${CONTAINER_TAG} $@
